SettingsLayout: display minute or minutes instead of minute(s)
monero-project/monero-gui pull request #2893
Opened 2020-05-09 16:42 UTC by rating89us

2020-05-13 13:36 UTC, selsta commented on pages/settings/SettingsLayout.qml
> +                return qsTr("Every ") + value + " " + minutes + translationManager.emptyString;
```suggestion
                return "%1 %2 %3".arg(qsTr("Every")).arg(value).arg(minutes) + translationManager.emptyString;
```

Else translators have to retranslate `"Every"`.

2020-05-13 13:46 UTC, xiphon requested changes
I don't like the patch. It only bloats the code and adds more work to translators.

And i guess some languages have more complex rules.

@erciccione

2020-05-13 15:13 UTC, erciccione requested changes
Singulars / plurals are always hard to deal with, especially because of the little context translators can extrapolate. This string is a perfect example. I think would be better to just leave this string as it is, to give translators more flexibility.

2020-05-17 13:27 UTC, selsta commented
`qsTr("Every %n second(s)", "0", value)` solves the plural problem. See #2915

2026-09-07 23:00 UTC, selsta commented
Superseded by #4591

2026-09-07 23:00 UTC, closed without merging