Receive: add search transactions button
monero-project/monero-gui pull request #3216
Opened 2020-11-07 22:20 UTC by rating89us

Requires #3215 and #3208 

This button will open Transactions page and search all sent and received transactions from this address.

![image](https://user-images.githubusercontent.com/45968869/98452445-b9e72b80-214f-11eb-801b-0da6b39fce1a.png)

2020-12-11 11:47 UTC, xiphon commented
Please use FontAwesome icon

2020-12-12 16:07 UTC, rating89us commented
Do you want to use FontAwesome icon just for this new button, or for all three buttons (search, edit and copy to clipboard)?

2020-12-12 20:56 UTC, xiphon commented
At least for the new button. Would love replacing all three buttons but think it is out of the current PR scope.

2020-12-13 11:33 UTC, selsta commented
I would prefer if we keep the current icons, as they were custom designed for the GUI. Using FontAwesome for new icons is obviously fine.

2021-05-18 22:52 UTC, rating89us commented
done

2021-05-18 23:37 UTC, selsta requested changes
You can use this code, it is simpler and looks closer like the other buttons. Also no changes to StandardButton required.

```
MoneroComponents.IconButton {
    fontAwesomeFallbackIcon: FontAwesome.searchPlus
    fontAwesomeFallbackSize: 22
    color: MoneroComponents.Style.defaultFontColor
    fontAwesomeFallbackOpacity: isOpenGL ? 0.5 : 0.8
    Layout.preferredWidth: 23
    Layout.preferredHeight: 21

    onClicked: doSearchInHistory(address)
}
```

2021-05-19 22:24 UTC, selsta approved these changes

2021-05-21 01:36 UTC, selsta commented on pages/Receive.qml
> +                                fontAwesomeFallbackOpacity: isOpenGL ? 0.5 : 0.8
```suggestion
                                fontAwesomeFallbackOpacity: 0.5
```

#3491

2021-05-22 21:01 UTC, selsta approved these changes

2021-06-01 06:36 UTC, merged