Mining: add info to start gui as admin for p2pool installation
monero-project/monero-gui pull request #3946
Opened 2022-06-10 18:01 UTC by selsta

Closes #3943

2022-06-11 02:48 UTC, devhyper requested changes

2022-06-11 02:48 UTC, devhyper commented on pages/Mining.qml
> +        errorPopup.text = qsTr("P2Pool installation failed.") + isWindows ? (" " + qsTr("Try starting the program with administrator privilges.")) : ""
```suggestion
        errorPopup.text = qsTr("P2Pool installation failed.") + isWindows ? (" " + qsTr("Try starting the program with administrator privileges.")) : ""
```

2022-06-11 16:22 UTC, selsta commented on pages/Mining.qml
> +        errorPopup.text = qsTr("P2Pool installation failed.") + isWindows ? (" " + qsTr("Try starting the program with administrator privilges.")) : ""
Thanks, fixed.

2022-07-04 15:38 UTC, plowsof commented
changes where requested and made LGTM

2022-07-04 15:38 UTC, plowsof approved these changes

2022-07-08 17:48 UTC, merged